-- Truncates all table data by disabling then enabling constraints
BEGIN
  FOR C IN (SELECT TABLE_NAME, CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'R')
  LOOP
    EXECUTE IMMEDIATE ('ALTER TABLE ' || C.TABLE_NAME || ' DISABLE CONSTRAINT ' || C.CONSTRAINT_NAME);
  END LOOP;
  
  FOR C IN (SELECT TABLE_NAME FROM USER_TABLES)
  LOOP
    EXECUTE IMMEDIATE ('TRUNCATE TABLE ' || C.TABLE_NAME);
  END LOOP;
  
  FOR C IN (SELECT TABLE_NAME, CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'R')
  LOOP
    EXECUTE IMMEDIATE ('ALTER TABLE ' || C.TABLE_NAME || ' ENABLE CONSTRAINT ' || C.CONSTRAINT_NAME);
  END LOOP;
END;

-- Truncates all table data by disabling then enabling constraints with an exclusion clause
BEGIN
  FOR C IN (SELECT TABLE_NAME, CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'R')
  LOOP
    EXECUTE IMMEDIATE ('ALTER TABLE ' || C.TABLE_NAME || ' DISABLE CONSTRAINT ' || C.CONSTRAINT_NAME);
  END LOOP;
  
  FOR C IN (SELECT TABLE_NAME FROM USER_TABLES WHERE NOT TABLE_NAME = 'MY_TABLE_NAME')
  LOOP
    EXECUTE IMMEDIATE ('TRUNCATE TABLE ' || C.TABLE_NAME);
  END LOOP;
  
  FOR C IN (SELECT TABLE_NAME, CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'R')
  LOOP
    EXECUTE IMMEDIATE ('ALTER TABLE ' || C.TABLE_NAME || ' ENABLE CONSTRAINT ' || C.CONSTRAINT_NAME);
  END LOOP;
END;

